consumes:
- application/json
- application/xml
- application/gob
- application/x-gob
definitions:
  FilterPayload:
    example:
      filter:
      - property: Amet nulla iste aliquam quod placeat debitis.
        value: Eos omnis.
      - property: Amet nulla iste aliquam quod placeat debitis.
        value: Eos omnis.
      page: 2995079951151655992
      pageSize: 3366218651594481479
      sort:
        direction: Et nisi consequatur dolorem ducimus vero.
        property: Itaque explicabo et cum.
    properties:
      filter:
        description: Organizations filter.
        example:
        - property: Amet nulla iste aliquam quod placeat debitis.
          value: Eos omnis.
        - property: Amet nulla iste aliquam quod placeat debitis.
          value: Eos omnis.
        items:
          $ref: '#/definitions/FilterProperty'
        type: array
      page:
        description: Page number (1-based).
        example: 2995079951151655992
        format: int64
        type: integer
      pageSize:
        description: Items per page.
        example: 3366218651594481479
        format: int64
        type: integer
      sort:
        $ref: '#/definitions/OrderSpec'
    required:
    - page
    - pageSize
    title: FilterPayload
    type: object
  FilterProperty:
    example:
      property: Amet nulla iste aliquam quod placeat debitis.
      value: Eos omnis.
    properties:
      property:
        description: Property name
        example: Amet nulla iste aliquam quod placeat debitis.
        type: string
      value:
        description: Property value to match
        example: Eos omnis.
        type: string
    required:
    - property
    - value
    title: FilterProperty
    type: object
  OrderSpec:
    example:
      direction: Et nisi consequatur dolorem ducimus vero.
      property: Itaque explicabo et cum.
    properties:
      direction:
        description: Sort order. Can be 'asc' or 'desc'.
        example: Et nisi consequatur dolorem ducimus vero.
        type: string
      property:
        description: Sort by property
        example: Itaque explicabo et cum.
        type: string
    required:
    - property
    - direction
    title: OrderSpec
    type: object
  UserProfilePage:
    description: UserProfilePage media type (default view)
    example:
      items:
      - company: Reprehenderit enim doloribus molestiae.
        companyRegistrationNumber: Dolorem illum aut.
        createdOn: 7249765961036167632
        email: fatima@stracke.name
        fullName: Velit assumenda.
        taxNumber: Rerum in ipsam odio beatae possimus harum.
        userId: Vel repudiandae omnis iste possimus possimus.
      - company: Reprehenderit enim doloribus molestiae.
        companyRegistrationNumber: Dolorem illum aut.
        createdOn: 7249765961036167632
        email: fatima@stracke.name
        fullName: Velit assumenda.
        taxNumber: Rerum in ipsam odio beatae possimus harum.
        userId: Vel repudiandae omnis iste possimus possimus.
      page: 7680382655718267873
      pageSize: 6951309304972377004
    properties:
      items:
        description: User profile list
        example:
        - company: Reprehenderit enim doloribus molestiae.
          companyRegistrationNumber: Dolorem illum aut.
          createdOn: 7249765961036167632
          email: fatima@stracke.name
          fullName: Velit assumenda.
          taxNumber: Rerum in ipsam odio beatae possimus harum.
          userId: Vel repudiandae omnis iste possimus possimus.
        - company: Reprehenderit enim doloribus molestiae.
          companyRegistrationNumber: Dolorem illum aut.
          createdOn: 7249765961036167632
          email: fatima@stracke.name
          fullName: Velit assumenda.
          taxNumber: Rerum in ipsam odio beatae possimus harum.
          userId: Vel repudiandae omnis iste possimus possimus.
        items:
          $ref: '#/definitions/userProfile'
        type: array
      page:
        description: Page number (1-based).
        example: 7680382655718267873
        format: int64
        type: integer
      pageSize:
        description: Items per page.
        example: 6951309304972377004
        format: int64
        type: integer
    title: 'Mediatype identifier: application/microkubes.user-profile-page+json; view=default'
    type: object
  UserProfilePayload:
    description: UserProfile data
    example:
      company: Est necessitatibus possimus autem.
      companyRegistrationNumber: Est exercitationem.
      email: haven.shanahan@hilpert.info
      fullName: Nemo atque sunt impedit occaecati magni.
      taxNumber: Suscipit perferendis similique qui itaque.
    properties:
      company:
        description: Company name
        example: Est necessitatibus possimus autem.
        type: string
      companyRegistrationNumber:
        description: Company registration number
        example: Est exercitationem.
        type: string
      email:
        description: Email of user
        example: haven.shanahan@hilpert.info
        format: email
        type: string
      fullName:
        description: Full name of the user
        example: Nemo atque sunt impedit occaecati magni.
        type: string
      taxNumber:
        description: Tax number
        example: Suscipit perferendis similique qui itaque.
        type: string
    required:
    - fullName
    - email
    title: UserProfilePayload
    type: object
  error:
    description: Error response media type (default view)
    example:
      code: invalid_value
      detail: Value of ID must be an integer
      id: 3F1FKVRR
      meta:
        timestamp: 1458609066
      status: "400"
    properties:
      code:
        description: an application-specific error code, expressed as a string value.
        example: invalid_value
        type: string
      detail:
        description: a human-readable explanation specific to this occurrence of the
          problem.
        example: Value of ID must be an integer
        type: string
      id:
        description: a unique identifier for this particular occurrence of the problem.
        example: 3F1FKVRR
        type: string
      meta:
        additionalProperties: true
        description: a meta object containing non-standard meta-information about
          the error.
        example:
          timestamp: 1458609066
        type: object
      status:
        description: the HTTP status code applicable to this problem, expressed as
          a string value.
        example: "400"
        type: string
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
  userProfile:
    description: userProfile media type (default view)
    example:
      company: Reprehenderit enim doloribus molestiae.
      companyRegistrationNumber: Dolorem illum aut.
      createdOn: 7249765961036167632
      email: fatima@stracke.name
      fullName: Velit assumenda.
      taxNumber: Rerum in ipsam odio beatae possimus harum.
      userId: Vel repudiandae omnis iste possimus possimus.
    properties:
      company:
        description: Company name
        example: Reprehenderit enim doloribus molestiae.
        type: string
      companyRegistrationNumber:
        description: Company registration number
        example: Dolorem illum aut.
        type: string
      createdOn:
        description: User profile created timestamp
        example: 7249765961036167632
        format: int64
        type: integer
      email:
        description: Email of user
        example: fatima@stracke.name
        format: email
        type: string
      fullName:
        description: Full name of the user
        example: Velit assumenda.
        type: string
      taxNumber:
        description: Tax number
        example: Rerum in ipsam odio beatae possimus harum.
        type: string
      userId:
        description: Unique user ID
        example: Vel repudiandae omnis iste possimus possimus.
        type: string
    required:
    - userId
    - createdOn
    title: 'Mediatype identifier: application/microkubes.user-profile+json; view=default'
    type: object
host: localhost:8082
info:
  description: API for managing UserProfile data.
  title: User Profile Microservice
  version: "1.0"
paths:
  /{userId}:
    get:
      description: Get a UserProfile by UserID
      operationId: userProfile#GetUserProfile
      parameters:
      - description: The user ID
        in: path
        name: userId
        required: true
        type: string
      produces:
      - application/microkubes.user-profile+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: GetUserProfile userProfile
      tags:
      - userProfile
    put:
      description: Update user profile
      operationId: userProfile#UpdateUserProfile
      parameters:
      - description: User ID
        in: path
        name: userId
        required: true
        type: string
      - description: UserProfile data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserProfilePayload'
      produces:
      - application/microkubes.user-profile+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: UpdateUserProfile userProfile
      tags:
      - userProfile
  /find:
    post:
      description: Find (filter) organizations by some filter.
      operationId: userProfile#FindUserProfile
      parameters:
      - in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/FilterPayload'
      produces:
      - application/microkubes.user-profile-page+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/UserProfilePage'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: FindUserProfile userProfile
      tags:
      - userProfile
  /me:
    get:
      description: Get a UserProfile by UserID
      operationId: userProfile#GetMyProfile
      produces:
      - application/microkubes.user-profile+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: GetMyProfile userProfile
      tags:
      - userProfile
    put:
      description: Update my profile
      operationId: userProfile#UpdateMyProfile
      parameters:
      - description: UserProfile data
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/UserProfilePayload'
      produces:
      - application/microkubes.user-profile+json
      - application/vnd.goa.error
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/userProfile'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: UpdateMyProfile userProfile
      tags:
      - userProfile
  /swagger-ui/{filepath}:
    get:
      operationId: swagger#/swagger-ui/*filepath
      parameters:
      - description: Relative file path
        in: path
        name: filepath
        required: true
        type: string
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
        "404":
          description: File not found
          schema:
            $ref: '#/definitions/error'
      schemes:
      - http
      summary: Download swagger-ui/dist
  /swagger.json:
    get:
      operationId: swagger#/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
      summary: Download swagger/swagger.json
produces:
- application/json
- application/xml
- application/gob
- application/x-gob
responses:
  OK:
    description: OK
    schema:
      $ref: '#/definitions/userProfile'
schemes:
- http
swagger: "2.0"
